// generate-sw.mjs
import { injectManifest } from "@serwist/build";

injectManifest({
  swSrc: "public/sw.js", // Use the JS file generated by Next.js
  swDest: "out/sw.js",  // The final worker for production
  globDirectory: "out",
  globPatterns: ["**/*.{html,js,css,png,txt}"],
  globIgnores: ["web.config"],
  injectionPoint: "self.__REPLACE_ME__", // Match your custom string
}).then(({ count, size }) => {
  console.log(`Precached ${count} files (${size} bytes)`);
});
